[Feat/member] 회원의 인조키와 이메일 조회에 대한 테스트 구현 && RestDocs 문서화
sosow0212/ChatUniv pull request #10
Opened 2023-06-22 12:37 UTC by JangAJang

- [x] 컨트롤러 단위 테스트 구현
- [x]  컨트롤러 통합 테스트 구현
- [x] RestDocs 문서화
- [x] Member.md에 진행상황 기록

2023-06-23 03:07 UTC, sosow0212 commented on src/docs/asciidoc/index.adoc
> +=== 회원 정보 조회
첫 Rest Docs 적용 아주 굿입니다

2023-06-23 03:08 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/controller/MemberControllerIntegrationTest.java
> +                .header("Authorization", BEARER_ + tokenResponse.getAccessToken())
이 부분은 RestAssured `preemptive`키워드를 학습해보세요~

2023-06-23 03:08 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/controller/MemberControllerIntegrationTest.java
> +            Assertions.assertTrue(bodyAsString.contains("memberId"));
다른 방법으로 body 검증을 해보는 건 어떨까요?

2023-06-23 03:08 UTC, sosow0212 requested changes
리뷰 확인해주세요~
추후에 태수랑 같이 로그인 중복을 어떻게 해결할지 고민하면 좋을 것 같습니다.

2023-06-25 02:37 UTC, JangAJang commented on src/test/java/mju/chatuniv/member/controller/MemberControllerIntegrationTest.java
> +            Assertions.assertTrue(bodyAsString.contains("memberId"));
body 검증 타입 이후에 response.body()를 이용한 검증으로 수정했습니다!!

2023-06-26 09:11 UTC, sosow0212 commented on src/main/java/mju/chatuniv/member/domain/Member.java
> +    public void changePassword(String newPassword) {
getter/setter가 일반적으로 맨 아래에 위치합니다.
그 아래에는 equals & hashcode가 있고요.

1. 따라서 해당 메서드는 위로 올려주는게 맞습니다
2. 매개변수 final 키워드 통일해주세요.

2023-06-26 09:15 UTC, sosow0212 commented on src/main/java/mju/chatuniv/member/application/service/MemberService.java
> +        changePasswordRequest.validateNewPassword();
해당 메서드를 보고 역할의 책임에 대해 말하려고 했으나,
바꾸려는 패스워드와 바꾸려는 패스워드 확인에 대한 검증에 대한 코드였네요.

이런 부분에 대한 검증을 DTO에서 하셨지만, DTO에는 로직이 들어가면 좋지 않습니다. 다만 위와 같이 최소한의 로직은 있어도 된다고 생각은 합니다.

이 검증에 대한 체킹을 DTO에서 해도 되지만, 서비스에서 하는 것은 어떨까요?
데이터를 옮겨주는 DTO에서 해당 로직을 수행하기보다는, 플로우를 다루는 서비스 레이어에서 검증하는 것이 저는 더 적절하다고 생각은 합니다.

하지만 재활용 가능성이 거의 없어서 해당 API에서 사용된다고 생각하면 그대로 진행하셔도 될 것 같습니다. 참고만~

2023-06-26 09:16 UTC, sosow0212 commented on src/main/java/mju/chatuniv/member/exception/NewPasswordsNotMatchingException.java
> +    public NewPasswordsNotMatchingException() {
개행 추가해주세요

2023-06-26 09:18 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/controller/MemberControllerUnitTest.java
>          //expected
`//expected`는 무엇일까요?

현재 `given-when-then` 패턴을 사용하고 있습니다.
컨벤션 지켜주세요.

given은 사용하지 않는다면 주석을 굳이 달아줄 필요는 없습니다.
다만 현재 `mockMvc.perform`의 로직은 when에 해당된다고 생각합니다. (when, 검증 then 둘다 해당)

따라서 `// when & then`으로 고쳐보는 건 어떨까요?

2023-06-26 09:19 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
> +                () -> assertEquals(expected, response.getMemberId() == id),
위에 리뷰를 놓쳤는데, 현재 구조에서 @DirtiesContext를 사용할 필요가 있을까요?
이 어노테이션 자체가 환경을 분리해주는 점은 유용하지만, 테스트 속도를 저하시킵니다.

따라서 필요한 부분이 나오면 그때 쓰는 건 어떨까요?

2023-06-26 09:20 UTC, sosow0212 requested changes
리뷰 확인해주세요~

2023-06-26 09:56 UTC, sosow0212 approved these changes

2023-06-26 09:57 UTC, kimtaesoo99 approved these changes

2023-06-26 10:07 UTC, merged