[Feat/comment] comment 구현
sosow0212/ChatUniv pull request #22
Opened 2023-07-15 15:12 UTC by eom-tae-in

2023-07-17 14:24 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/application/service/BoardCommentService.java
> +        Board board = boardRepository.findById(boardId).orElseThrow();
`.orElseThrow()` 개행 추가해주세요~

2023-07-17 14:26 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/controller/BoardCommentController.java
> +@RequestMapping("/api")
중요한 어노테이션일 수록 클래스와 가깝게 두는 것은 어떨까요?

2023-07-17 14:35 UTC, sosow0212 requested changes
잘 구현해주셨네요~
다이나믹 테스트로 구현체들의 테스트 중복을 막은게 인상 깊었어요.

몇 가지만 확인해주세요!

2023-07-17 14:35 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/domain/CommentRepository.java
> +    @Query("select c from Comment c join BoardComment bc on c.id = bc.id where bc.board.id = :boardId")
오~ 현재 구조에서는 지연로딩이고, get()으로 가져올 때 N+1 문제가 발생할텐데, 이렇게  Fetch Join 해서 가져온다면 N+1문제가 발생하지 않겠네요

2023-07-17 14:35 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/controller/BoardControllerUnitTest.java
>  import mju.chatuniv.member.domain.Member;
예외인 경우는 테스트를 하지 않아도 될까요?
프론트엔드가 어떤 예외인지 어떻게 알까요!

2023-07-17 14:35 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/application/service/EachCommentService.java
> +public interface EachCommentService {
범용적이라면 Each보다는 그냥 CommentService라는 네이밍을 두고, 구현하면서 구현체의 이름을 만들어주는 것은 어떨까요?

2023-07-17 14:35 UTC, sosow0212 commented on src/test/java/mju/chatuniv/comment/controller/intergration/BeanUtils.java
> +    public static List<EachCommentService> getBeansOfType() {
다이나믹 테스트를 하기 위해서 만든 클래스일까요?

2023-07-17 14:35 UTC, sosow0212 commented on src/test/java/mju/chatuniv/comment/controller/intergration/CommonCommentControllerIntegrationTest.java
> +    List<DynamicTest> create_comment_by_id() {
다이나믹 테스트로 `EachCommentService`를 구현한 구현체들의 테스트를 모두 해결해줬네요 👍

2023-07-20 00:42 UTC, JangAJang commented on src/main/java/mju/chatuniv/comment/application/service/BoardCommentService.java
> +        Board board = boardRepository.findById(boardId).orElseThrow();
추가로, 위에 있던 것과 동일하게 throw(() -> new BoardNotFoundException(boardId))해주는 것이 좋아 보입니다.

2023-07-20 00:42 UTC, JangAJang commented on src/main/java/mju/chatuniv/comment/controller/CommentController.java
> +                                                         @RequestBody final CommentRequest commentRequest) {
바디 요청이 있다면 @Valid를 이용해서 유효값 검증을 추가하는건 어떨까요?

2023-07-30 07:10 UTC, kimtaesoo99 commented on src/test/java/mju/chatuniv/board/controller/BoardControllerUnitTest.java
>  import mju.chatuniv.member.domain.Member;
> 예외인 경우는 테스트를 하지 않아도 될까요? 프론트엔드가 어떤 예외인지 어떻게 알까요!

혹시 어떤 부분을 말씀해주시는 건가요?
현재 리뷰를 해주신 부분은 게시판에 대한 부분인데, 이에 대한 부분은 예외처리가 진행되어있습니다! 
혹시 어떤 부분인지 다시한번 확인 부탁드립니다.

2023-07-30 07:11 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/comment/controller/intergration/BeanUtils.java
> +    public static List<EachCommentService> getBeansOfType() {
해당 클래스는 ApplicationContext에서 빈을 특정 클래스 타입으로 조회하기 위한 클래스입니다~

2023-07-30 09:11 UTC, kimtaesoo99 commented on src/main/java/mju/chatuniv/comment/domain/CommentRepository.java
> +    @Query("select c from Comment c join BoardComment bc on c.id = bc.id where bc.board.id = :boardId")
> 오~ 현재 구조에서는 지연로딩이고, get()으로 가져올 때 N+1 문제가 발생할텐데, 이렇게 Fetch Join 해서 가져온다면 N+1문제가 발생하지 않겠네요

지연 로딩(LAZY loading) 전략을 사용하여 연관된 엔티티의 식별자(ID)만을 가져와서 프록시(proxy) 객체로 처리하는 것으로 동작합니다. 따라서 id만을 비교하기 때문에 N+1문제가 발생하지는 않았습니다.

2023-07-31 02:54 UTC, sosow0212 approved these changes
수고하셨습니다 👍
리뷰 내용 확인하고 Merge하셔도 될 것 같습니다~

2023-07-31 02:54 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/application/dto/CommentResponse.java
> +    public CommentResponse(final Long commentId, final String content) {
접근 제어자를 private로 바꿔야할 것 같아요

2023-07-31 02:54 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/application/service/BoardCommentService.java
> +        findBoard(boardId);
이 메서드를 호출한 이유가 있나요?

2023-07-31 02:54 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/application/service/CommentService.java
> +    CommentResponse create(Long boardId, Member member, CommentRequest commentRequest);
`create`메서드의 인자가 `boardId`인데, 그럼 이 인터페이스는 `Board`도메인에서만 사용하나요?

2023-07-31 02:54 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/domain/Comment.java
> +    public Member getMember() {
`get()`메서드는 맨 밑으로 내리는 건 어떨까요?

2023-08-15 09:23 UTC, kimtaesoo99 approved these changes

2023-08-15 09:24 UTC, merged