[Feat/31] 통계 기능 추가
sosow0212/ChatUniv pull request #44
Opened 2023-09-09 06:36 UTC by kimtaesoo99

통계기능 추가 
기존의 방식은 DB에 1시간마다 접근하여 데이터를 가져오고, 단어의 frequency를 0으로 초기화하는 방식이었습니다.

이를 DB접근없이 Map 자료구조를 사용하여 자바 코드로만 구현해보았습니다.

위 방식을 사용하면 DB접근이 사라지고, 실제 실시간 검색어를 볼 수 있습니다.
다만 서버가 터지면 데이터가 사라진다는 단점이 존재하고, 실제 DB에 저장하지 않기에 id값이 null로 나오게됩니다.
만약 id값이 필요하다면 구조의 변경이 필수로 생기게됩니다.

리뷰 부탁드립니다.

2023-09-11 09:19 UTC, sosow0212 requested changes
일단 저번에도 추후 상황 보고 개선하기로 한 부분이므로 추후 개선이 필요해보입니다.
현재는 자바 코드레벨로 캐싱을 해서 실시간검색어를 내려줘도 되지만, 이 부분에서 문제점(서버가 다운되면 검색어 데이터도 날아가는 문제)이 있는데요. 이 부분은 추후에 같이 해결해보면 좋을 것 같습니다.

추가적으로 테스트코드만 작성해주시고 다시 요청 주세요!

2023-09-11 09:19 UTC, sosow0212 commented on src/main/java/mju/chatuniv/statistic/application/StatisticService.java
> +public class StatisticService {
테스트도 있으면 좋을 것 같습니다

2023-09-12 12:00 UTC, sosow0212 approved these changes
수고하셨습니다

2023-09-12 12:01 UTC, eom-tae-in approved these changes

2023-09-12 13:44 UTC, merged