[Feat/member] Member api 기능 구현
sosow0212/ChatUniv pull request #5
Opened 2023-06-11 13:12 UTC by JangAJang

- [ ] 마이페이지 조회 기능 구현
    - [ ] 서비스 로직 구현
    - [ ] 서비스 로직 테스트
    - [ ] 컨트롤러 로직 구현
    - [ ] 컨트롤러 로직 테스트
- [ ] 회원 비밀번호 수정 기능 구현
    - [ ] 서비스 로직 구현
    - [ ] 서비스 로직 테스트
    - [ ] 컨트롤러 로직 구현
    - [ ] 컨트롤러 로직 테스트
- [ ] 회원 삭제 기능 구현
    - [ ] 서비스 로직 구현
    - [ ] 서비스 로직 테스트
    - [ ] 컨트롤러 로직 구현
    - [ ] 컨트롤러 로직 테스트

2023-06-11 13:34 UTC, sosow0212 commented on src/main/java/mju/chatuniv/member/application/service/MemberService.java
> +    public MemberResponse getMemberInfo(final Member member){
1. `info` 라는 네이밍은 추상적이어서 피하는 게 좋습니다.
2. `get`이라는 네이밍 또한 `member` 객체를 레포지토리에서 가져오는 경우 null인 경우가 있을 수 있기에 `find`라는 명칭(혹은 그 외)이 적절할 것 같습니다.

2023-06-11 13:34 UTC, sosow0212 requested changes
네이밍 리뷰 참고 부탁드립니다.

2023-06-11 13:39 UTC, sosow0212 commented on src/main/java/mju/chatuniv/member/application/service/MemberService.java
> +        return MemberResponse.from(member);
아마도 멤버를 찾아오는 api 같습니다.

파라미터로 member로 받은 이유는 로그인 한 유저를 ArgumentResolver로 찾아온 후에 서비스로 넘겨서 반환하려고 하는 것으로 추측되는데,

프론트엔드에서 이 API를 사용하는 이유는 아마 `Member 조회로 페이지 구현`이 목적일 것 같습니다. 따라서 위와 같이 ArgumentResolver로 받아오는 것이 아닌, 따로 컨트롤러단에서 유저의 이름을 받아서 Repository에서 찾아와주는 것이 좋다고 생각합니다.

만약 현재 로그인 한 멤버를 가져오는 것이라면 이렇게 진행하셔도 됩니다. (네이밍만 변경 필요할듯)

2023-06-11 13:40 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
> +        assertThat(response.getEmail().equals(email)).isEqualTo(expected);
`assertThat()` 메서드로 검증을 여러 개 하는 경우 어떤 일이 벌어질까요?

현재 경우에서는 두 가지의 검증을 하고 있는데, 만약 첫 번째 검증이 실패한다면 두 번째 검증은 시도를 안 하게 됩니다.

따라서 `assertAll()` 키워드를 검색해서 적용해보는 것을 추천드립니다.

2023-06-11 13:40 UTC, JangAJang commented on src/main/java/mju/chatuniv/member/application/service/MemberService.java
> +        return MemberResponse.from(member);
로그인 후 마이페이지 구현의 부분이어서 네이밍 수정하겠습니다.

2023-06-11 13:40 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
> +        //then
`//then` 위에 개행 하나 추가해서 가독성 올려주십숑

2023-06-11 13:44 UTC, sosow0212 reviewed
추가적으로 피드백 확인 부탁드립니다.

2023-06-11 13:44 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
> +    public void get_my_info(final int id, final String email, final boolean expected) throws Exception{
1. `Exception{` 정렬 부탁드립니다.
2. 테스트 메서드 명이 현재 메서드를 따라가는 것으로 보입니다. 테스트 메서드 명도 `info`라는 네이밍은 추상적이니 다르게 바꿔주세요. + `get`도 `find` 같은 것으로 정정 부탁드립니다. (조회시 null이거나 예외일 수 있으니)
3. 예외도 테스트 부탁드립니다. (이건 통합테스트가 아니고 단위테스트에서 해도 됩니다. 빈을 모두 올리는 통합테스트는 느리기 때문에요. 근데 적절하다고 생각하면 그대로 진행해도 됩니다. 추후에 컨벤션을 따로 정할 것이기 때문이죵!)

2023-06-11 13:44 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
1. SpringBootTest(RANDOM_PORT or DEFINED_PORT) 로 사용하기
2. SpringBootTest + @Transactional
3. @DirtiesContext

1번과 2번의 경우의 차이점은 무엇일까요?
그리고 @DirtiesContext는 무엇이고 언제쓸까요?

이건 학습 차원에서 리뷰 남깁니다~

2023-06-16 06:21 UTC, JangAJang commented on src/main/java/mju/chatuniv/member/application/service/MemberService.java
> +    public MemberResponse getMemberInfo(final Member member){
getMemberInfo  -> getUsingMemberIdAndEmail로 메서드명 변경했습니다.

2023-06-16 06:22 UTC, JangAJang commented on src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
> +        assertThat(response.getEmail().equals(email)).isEqualTo(expected);
assertAll(
                () -> assertTrue(response.getMemberId() == id),
                () -> assertTrue(response.getEmail().equals(email))
        );
메서드 방식 수정했습니다.

2023-06-16 06:23 UTC, JangAJang commented on src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
> +        //then
개행 추가했습니다.

2023-06-16 06:23 UTC, JangAJang commented on src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
> +    public void get_my_info(final int id, final String email, final boolean expected) throws Exception{
1. 정렬해서 커밋 했습니다. 
2. get_log_in_members_id_and_email로 메서드명 변경했습니다.

2023-06-16 06:43 UTC, JangAJang commented on src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
1. 해당 포트에서 스프링 컨테이너를 실행시킨다. 
   랜덤포트, 혹은 application.yml에서 지정한 포트로 listen하는지 정한다. 실제 서블릿 환경을 제공한다. 
   하지만, 롤백이 되지 않아 테스트 격리(각 테스트가 서로에게 영향을 끼치지 않는 상태)가 이루어지지 않는다. 
2. 서블릿 환경을 구성하지 않고, 일반적인 ApplicationContext를 로드한다. 테스트시에 롤백이 가능하다. 
3. 스프링 컨테이너 자체를 재생성한다. ApplicationContext 공유를 막으므로 테스트 격리를 할 수 있지만, 속도가 매우 느리다는 단점이 있다.

2023-06-18 05:01 UTC, kimtaesoo99 commented
현재 멤버 도메인에서 정적팩토리 메서드가 전부 from으로 되어있는데, 의도한건지 궁금합니다.

정적 팩토리 메서드 네이밍 컨벤션
from : 하나의 매개 변수를 받아서 객체를 생성
of : 여러개의 매개 변수를 받아서 객체를 생성
getInstance | instance : 인스턴스를 생성. 이전에 반환했던 것과 같을 수 있음.
newInstance | create : 새로운 인스턴스를 생성
get[OtherType] : 다른 타입의 인스턴스를 생성. 이전에 반환했던 것과 같을 수 있음.
new[OtherType] : 다른 타입의 새로운 인스턴스를 생성.

2023-06-18 05:09 UTC, kimtaesoo99 commented on src/main/java/mju/chatuniv/member/controller/MemberController.java
> +    @GetMapping("")
("")이 부분을 생략해도 되는데, 일부로 살려둔것인지 궁금합니다.

2023-06-18 14:15 UTC, sosow0212 commented on src/main/java/mju/chatuniv/member/controller/MemberController.java
> +    @GetMapping("")
동감입니다

2023-06-18 14:16 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/controller/MemberControllerUnitTest.java
> +    @DisplayName("현재 로그인한 회원의 인조키와 이메일을 반환한다.")
@Test와 @DisplayName중 어떤게 메서드의 이름과 가까워야할까요?
컨벤션의 범위이긴하지만, 중요한 것일 수록 메서드와 가까워야한다고 생각합니다.

2023-06-18 14:16 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/controller/MemberControllerUnitTest.java
> +    public void get_using_member_id_and_email() throws Exception{
정렬 부탁드립니다.

2023-06-18 14:19 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/controller/MemberControllerUnitTest.java
> +                .header(HttpHeaders.AUTHORIZATION, BEARER_+ createTokenByMember(member)))
로그인을 해야 진행되는 API를 테스트할 때에는 매번 이렇게 해야할까요?
더 좋은 방법이 있으면 변경 부탁드리고,

이렇게 진행해야 되는게 최선이라고 생각하시면 추후 테스트를 위해 helper로 분리 부탁드립니다. 추가적으로 helper로 분리한다면, 이를 상속 받는 더 좋은 전략도 있을 것 같네요.

2023-06-18 14:19 UTC, sosow0212 reviewed
코멘트 추가합니다~

2023-06-18 14:32 UTC, JangAJang commented on src/main/java/mju/chatuniv/member/controller/MemberController.java
> +    @GetMapping("")
컨벤션 수정하며 같이 수정했습니다

2023-06-18 14:32 UTC, JangAJang commented on src/test/java/mju/chatuniv/member/controller/MemberControllerUnitTest.java
> +    @DisplayName("현재 로그인한 회원의 인조키와 이메일을 반환한다.")
수정했습니다.

2023-06-18 14:33 UTC, JangAJang commented on src/test/java/mju/chatuniv/member/controller/MemberControllerUnitTest.java
> +    public void get_using_member_id_and_email() throws Exception{
정렬 했습니다.

2023-06-19 09:00 UTC, sosow0212 approved these changes
이정도면 어프루브 하겠습니다!
다른 부분은 개발하면서 고쳐가면 될 것 같습니다.

추후에 테스트에서 토큰 만드는 부분만 다른 곳에서 재사용 할 수 있도록 분리만 해주시면 될 것 같습니다

2023-06-19 17:32 UTC, kimtaesoo99 approved these changes

2023-06-20 05:03 UTC, merged