feat: 예외처리 테스트 메서드 추가
sosow0212/ChatUniv pull request #59
Opened 2023-09-21 14:27 UTC by kimtaesoo99

- [x] 예외처리 테스트 메서드 추가

2023-09-22 00:00 UTC, JangAJang approved these changes
고생하셨습니다!

2023-09-26 14:10 UTC, JangAJang requested changes

2023-09-26 14:10 UTC, JangAJang commented on src/main/java/mju/chatuniv/board/domain/Board.java
>      private static void validationBoard(final String title, final String content) {
함수 네이밍 동사형으로 수정하는게 낫지 않을까요?

2023-09-26 14:10 UTC, JangAJang commented on src/main/java/mju/chatuniv/board/service/BoardService.java
> +        Board board = Board.of(boardRequest.getTitle(), boardRequest.getContent(), member);
정적 팩토리 메서드 네이밍 수정한 부분 좋은 것 같습니다! 추가적으로, 다른 사용하기 좋은 네이밍 들이 있길래 공유드립니다!
of : 입력받은 파라미터들을 검증하고 인스턴스화 시킨다. 파라미터의 데이터를 convert(조작, 전환)하지 않는다.  
from : 입력 파라미터를 타겟 객체의 인스턴스화 시킨다. 
parse : 타겟 객체의 인스턴스화 시키기 위해 일련의 문자열을 파싱해 객체화시킨다. 

외에도 format, get, is, with, plus, minus, to, at등이 일반 인스턴스 메서드로 사용한다고 합니다. 찾아보면 좋은 것 같습니다!

2023-09-26 14:10 UTC, JangAJang commented on src/main/java/mju/chatuniv/chat/service/ChatService.java
> +        chat.validateOwner(member);
객체지향적으로 하기 위해 객체 메서드로 분리하신게 좋습니다!

2023-09-26 14:10 UTC, JangAJang commented on src/main/java/mju/chatuniv/member/exception/exceptions/EmailAlreadyExistsException.java
> +    public EmailAlreadyExistsException(final String password) {
password파라미터가 아닌, email파라미터가 가는게 맞지 않을까요?

2023-09-26 14:40 UTC, eom-tae-in commented on src/main/java/mju/chatuniv/board/service/BoardService.java
> +        Board board = Board.of(boardRequest.getTitle(), boardRequest.getContent(), member);
좋은 정보 감사합니다!

2023-09-27 02:35 UTC, sosow0212 requested changes
수고하셨습니다! 몇 부분만 확인해주세요~

2023-09-27 02:35 UTC, sosow0212 commented on src/main/java/mju/chatuniv/auth/controller/AuthController.java
> +    public ResponseEntity<MemberResponse> register(@RequestBody @Valid final MemberRequest memberRequest) {
MemberRequest로 네이밍을 변경하신 이유가 있나요?

2023-09-27 02:35 UTC, sosow0212 commented on src/main/java/mju/chatuniv/auth/infrastructure/JwtTokenProvider.java
> +    public String getPayload(final String token) {
👍

2023-09-27 02:35 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/domain/Board.java
> +        validateBoard(title, content);
네이밍 변경 굿

2023-09-27 02:35 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/service/BoardService.java
> -
이런 개행 없애는 것도 좋지만, 가독성을 위해서 개행을 추가하는 것도 좋아보입니다!
기준이 생기면 더 좋을 것 같아요 ㅎㅎ

2023-09-27 02:35 UTC, sosow0212 commented on src/test/java/mju/chatuniv/auth/controller/AuthControllerUnitTest.java
> +    void fail_to_sign_up_with_duplicated_email() throws Exception {
예외 응답은 response로 안 줘도 될까요?
문서화에는 response도 포함되어야할 것 같습니다

2023-09-27 02:35 UTC, sosow0212 commented on src/test/java/mju/chatuniv/auth/service/JwtAuthServiceUnitTest.java
> +        MemberRequest memberRequest = new MemberRequest("b@b.com", "1234");
만약 MemberRequest가 중복 코드를 줄이기 위해서 네이밍을 변경한 거라면 좋은 의도이긴 하지만, Login, Create라는 네이밍을 명시하는 것과 이렇게 하는 것의 차이는 무엇일까요?

MemberRequest가 어떤 요청을 하는지 모를 수 있지 않을까요?

2023-09-27 04:50 UTC, eom-tae-in commented on src/main/java/mju/chatuniv/auth/controller/AuthController.java
> +    public ResponseEntity<MemberResponse> register(@RequestBody @Valid final MemberRequest memberRequest) {
회원 가입을 할 때 사용하는 MemberCreateRequest와 로그인을 할 때 사용하는 MemberLoginRequest의 내부 로직이 모두 동일하여 하나로 합쳐서 사용하면 좋을 것 같아보였습니다. 그러면서 네이밍을 MemberRequest로 바꾸게 되었습니다.

2023-09-27 04:52 UTC, eom-tae-in commented on src/main/java/mju/chatuniv/board/service/BoardService.java
> -
좋습니다! 회의를 통해 기준이 정해지면 다시 적용하도록 하겠습니다.

2023-09-27 04:55 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/auth/service/JwtAuthServiceUnitTest.java
> +        MemberRequest memberRequest = new MemberRequest("b@b.com", "1234");
아 MemberLoginRequest와 MemberCreateRequest를 따로 만든 이유가 있었네요. 
위의 두가지 클래스를 모두 MemberRequest로 바꾸면 다른 사람이 이해하는데 방해가 될 거 같네요.
수정하도록 하겠습니다.

2023-09-27 05:03 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/auth/controller/AuthControllerUnitTest.java
> +    void fail_to_sign_up_with_duplicated_email() throws Exception {
adoc 문서에서  http-response.adoc을 통해 HTTP의 응답 상태코드, 응답 헤더, 응답 바디에 대한 설명 및 예제를 파일로 제공 할 수 있어서 따로 추가 하지 않았습니다.

2023-09-27 06:07 UTC, JangAJang approved these changes

2023-09-27 06:17 UTC, sosow0212 approved these changes
수고하셨습니다

2023-09-27 06:17 UTC, merged