feat: 마이페이지 기능 구현
sosow0212/ChatUniv pull request #60
Opened 2023-09-23 07:52 UTC by JangAJang

- [ ] 회원의 채팅방 페이지 조회 기능 구현
    - [ ] 채팅방을 반환할 형태 구체화
    - [ ] 리포지토리 로직 구현
    - [ ] 서비스 로직 구현
    - [ ] 컨트롤러 로직 구현
    - [ ] 서비스 통합 테스트
    - [ ] 컨트롤러 단위 테스트
    - [ ] 컨트롤러 통합 테스트
- [ ] 회원의 댓글 조회 기능 구현
    - [ ] 댓글을 반환할 형태 구체화
    - [ ] 리포지토리 로직 구현
    - [ ] 서비스 로직 구현
    - [ ] 컨트롤러 로직 구현
    - [ ] 서비스 통합 테스트
    - [ ] 컨트롤러 단위 테스트
    - [ ] 컨트롤러 통합 테스트
- [ ] 회원의 게시물 조회 기능 구현
    - [ ] 게시물을 반환할 형태 구체화
    - [ ] 리포지토리 로직 구현
    - [ ] 서비스 로직 구현
    - [ ] 컨트롤러 로직 구현
    - [ ] 서비스 통합 테스트
    - [ ] 컨트롤러 단위 테스트
    - [ ] 컨트롤러 통합 테스트

2023-09-25 04:12 UTC, sosow0212 requested changes
해당 부분만 고쳐주세요~ 수고하셨습니다!

2023-09-25 04:12 UTC, sosow0212 commented on src/main/java/mju/chatuniv/member/controller/MemberController.java
> +    @GetMapping("/chats")
RESTful 원칙을 지키는 건 어떨까요?
`/api/members/{memberId}/chats` 혹은 `/api/members/me/chats` 이런식이면 좋을 것 같습니다!

2023-09-25 04:12 UTC, sosow0212 commented on src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
> +                        assertEquals(memberService.findMembersBoard(member).stream().map(BoardResponse::getTitle).collect(Collectors.toList()),
정렬만 맞추면 좋을 것 같아요~

2023-09-25 06:54 UTC, JangAJang commented on src/main/java/mju/chatuniv/member/controller/MemberController.java
> +    @GetMapping("/chats")
/api/members/me/chats 로 수정했습니다!

2023-09-25 07:02 UTC, JangAJang commented on src/test/java/mju/chatuniv/member/service/MemberServiceIntegrationTest.java
> +                        assertEquals(memberService.findMembersBoard(member).stream().map(BoardResponse::getTitle).collect(Collectors.toList()),
정렬 수정했습니다!

2023-09-25 07:35 UTC, sosow0212 approved these changes
작업하느라 수고하셨습니다!

2023-09-25 08:30 UTC, kimtaesoo99 reviewed
리뷰 추가했습니다.

2023-09-25 08:30 UTC, kimtaesoo99 commented on src/main/java/mju/chatuniv/member/service/service/MemberService.java
> +                .stream().map(BoardResponse::from).collect(Collectors.toList());
한 줄에 점을 하나만 찍도록 수정해주세요.

2023-09-25 08:30 UTC, kimtaesoo99 commented on src/main/java/mju/chatuniv/member/controller/MemberController.java
> +                .body(MembersChatRoomResponse.from(memberService.findMembersChat(member)));
다른 컨트롤러는 memberService.findMembersChat의 결과 List<Chat>을 명시적으로 보여주고 이를 from에 넣어주는데, 이곳은 바로 리턴에 사용합니다.

2023-09-26 10:04 UTC, JangAJang commented on src/main/java/mju/chatuniv/member/service/service/MemberService.java
> +                .stream().map(BoardResponse::from).collect(Collectors.toList());
리포지토리 조회된 데이터를 따로 변수로 받고, 각 체이닝은 한 줄에 하나씩 점이 찍히도록 줄바꿈처리했습니다.

2023-09-26 10:06 UTC, JangAJang commented on src/main/java/mju/chatuniv/member/controller/MemberController.java
> +                .body(MembersChatRoomResponse.from(memberService.findMembersChat(member)));
List를 변수로 따로 받고, 해당 변수를 ResponseEntity에서 from으로 처리하도록 수정했습니다.

2023-09-27 04:10 UTC, eom-tae-in approved these changes

2023-09-27 04:10 UTC, eom-tae-in commented on src/main/java/mju/chatuniv/member/controller/dto/MembersBoardResponse.java
> +        return this.boardResponses;
다른 dto에서는 this를 붙이지 않았는데 여기서 붙인 이유가 있나요???

2023-09-27 05:16 UTC, JangAJang commented on src/main/java/mju/chatuniv/member/controller/dto/MembersBoardResponse.java
> +        return this.boardResponses;
js 컨벤션이랑 헷갈린 것 같습니다. 제거했습니다.

2023-09-27 05:21 UTC, merged