[Feat/board] Board api 기능 구현
sosow0212/ChatUniv pull request #8
Opened 2023-06-20 04:19 UTC by kimtaesoo99

- [ ] 게시글 작성
    - [x] 서비스 로직 구현
    - [ ] 서비스 통합 테스트
    - [ ] 서비스 단위 테스트
    - [x] 컨트롤러 로직 구현
    - [x] 컨트롤러 통합 테스트
    - [ ]  컨트롤러 단위 테스트

- [ ] 게시글 단건 조회
    - [x] 서비스 로직 구현
    - [ ] 서비스 통합 테스트
    - [ ] 서비스 단위 테스트
    - [x] 컨트롤러 로직 구현
    - [x] 컨트롤러 통합 테스트
    - [ ]  컨트롤러 단위 테스트

- [ ] 게시글 전체 조회
    - [x] 서비스 로직 구현
    - [ ] 서비스 통합 테스트
    - [ ] 서비스 단위 테스트
    - [x] 컨트롤러 로직 구현
    - [x] 컨트롤러 통합 테스트
    - [ ]  컨트롤러 단위 테스트

- [ ] 게시글 수정
    - [x] 서비스 로직 구현
    - [ ] 서비스 통합 테스트
    - [ ] 서비스 단위 테스트
    - [x] 컨트롤러 로직 구현
    - [x] 컨트롤러 통합 테스트
    - [ ]  컨트롤러 단위 테스트

- [ ] 게시글  삭제
    - [x] 서비스 로직 구현
    - [ ] 서비스 통합 테스트
    - [ ] 서비스 단위 테스트
    - [x] 컨트롤러 로직 구현
    - [x] 컨트롤러 통합 테스트
    - [ ]  컨트롤러 단위 테스트

2023-06-20 04:31 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/BoardService.java
> +    public BoardAllResponse findAll(final Pageable pageable) {
보통 글을 전체 조회하면 최신 글부터 나오는데 예전 글부터 순차적으로 나오는 문제 해결해주세요.

2023-06-20 04:32 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/BoardService.java
> +    public BoardService(BoardRepository boardRepository) {
매개변수 final 키워드 통일 부탁드립니다

2023-06-20 04:33 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/BoardService.java
> +        return BoardResponse.of(board);
from, of 둘다 암묵적인 네이밍이지만 of로 한 이유가 무엇인가요?
List.of(a, b, c ...) 처럼 여러 인자를 받는 경우에 보통 of를 사용합니다.

2023-06-20 04:34 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/BoardService.java
> +            .orElseThrow(BoardNotFoundException::new);
로깅을 작성해주면 드는 비용에 비해서 엄청난 시간을 줄일 수 있습니다.
BoardNotFound에서 단순 에러를 표현하기보다는 어떤 게시글의 번호에 해당하는 게시글을 찾을 수 없다는 식으로 로깅을 해주는 것은 어떨까요?

2023-06-20 04:36 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/BoardService.java
> +    public String delete(final Long boardId, final Member member) {
restful에서 delete는 반환값이 필요할까요?
프론트가 `DELETE`는 메시지가 필요하지 않습니다. 예외코드로 삭제의 의미를 내포하기 때문입니다.

2023-06-20 04:38 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/BoardService.java
> +        board.update(boardRequest);
`Board` 객체가 `BoardRequest`에 대해 알아야할까요? request의 구조가 바뀐다면 어떻게 될까요

2023-06-20 04:39 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/dto/BoardAllResponse.java
> +    private BoardAllResponse(Page<BoardResponse> boards) {
final 키워드 통일해주세요 다른 부분도 마찬가지

2023-06-20 04:40 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/dto/BoardAllResponse.java
> +    private final boolean isNext;
`isNext`가 무엇을 의미할까요? 이런 네이밍보다는 `hasNextPage` 같은 명확한 네이밍은 어떨까요?

2023-06-20 04:41 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/dto/BoardRequest.java
> +    public BoardRequest(String title, String content) {
final 키워드 통일해주세요

2023-06-20 04:43 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +    public ResponseEntity<BoardResponse> find(@PathVariable("id") final Long id) {
나중에 카테고리나 다른 것들이 생긴다면 `id`라는 의미는 어떤 id를 의미하게 될까요?
현재 서비스의 확장성을 고려해서 보다 명확한 네이밍으로 변경해주세요.

2023-06-20 04:43 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +        return ResponseEntity.ok(boardService.find(id));
`find`는 무엇을 찾는다는 뜻일까요? 그리고 여기에 넘어가는 id 인자는 무엇인가요?

2023-06-20 04:44 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +    public ResponseEntity<BoardAllResponse> findALl(@PageableDefault final Pageable pageable) {
`findALl`은 무엇인가요? 오타 확인하고 제출해주세요

2023-06-20 04:44 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +    public ResponseEntity<BoardResponse> update(@PathVariable("id") final Long id, @JwtLogin final Member member,
다른 부분에서는 가독성을 위해서 파라미터 하나하나 개행을 추가해주고 있습니다.
@PathVariable과 @JwtLogin을 하나의 개행에서 적은 이유가 있나요?

2023-06-20 04:45 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +        return ResponseEntity.ok(boardService.delete(id, member));
삭제를 하면 컨텐츠가 없으니 204 상태코드를 사용하는 건 어떨까요?

2023-06-20 04:55 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/domain/Board.java
> +    @Lob
Lob 굿굿

2023-06-20 04:56 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/domain/Board.java
> +    public void update(final BoardRequest boardRequest) {
Board가 BoardRequest를 알면 뭐가 문제가 될까?

2023-06-20 04:56 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/exception/BoardContentBlankException.java
> +        super("Board의 내용이 비어있습니다.");
다른 리뷰에도 적었지만 다른 예외 전부 할 수 있다면 로깅 추가해주기

2023-06-20 04:58 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/BoardControllerIntegrationTest.java
> +            .header(HttpHeaders.AUTHORIZATION, BEARER_ + token)
RestAssured의 `preemptive` 키워드 학습해봐~

2023-06-20 04:59 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/BoardControllerIntegrationTest.java
> +        Pageable pageable = PageRequest.of(10,10);
정렬해주기

2023-06-20 05:00 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/BoardControllerIntegrationTest.java
> +            .statusCode(HttpStatus.OK.value());
다른 부분도 마찬가지인데 상태코드만 검증하면 될까?
여러 레이어가 연관되어 있는 E2E 테스트인데 값 검증도 필요할 것 같아
(우리 애초에 처음에 모든 테스트를 작성하자고 했기 때문에 )

2023-06-20 05:00 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/BoardControllerIntegrationTest.java
> +    void findAll_board() {
네이밍 컨벤션이 맞지 않아

2023-06-20 05:01 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/BoardControllerIntegrationTest.java
> +public class BoardControllerIntegrationTest {
단위 테스트는 안해도 될까?
RestDocs 생성, 모든 관련 예외까지 단위 테스트에서 진행해주는 게 좋아보일듯

2023-06-20 05:02 UTC, sosow0212 requested changes
리뷰 확인하고 고쳐주십쇼

2023-06-20 08:10 UTC, kimtaesoo99 commented
테스트 부분은 조금 더 학습후에 진행하겠습니다. 
1차적으로 수정하였습니다.

2023-06-20 08:12 UTC, kimtaesoo99 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +    public ResponseEntity<BoardResponse> update(@PathVariable("id") final Long id, @JwtLogin final Member member,
120줄을 기준으로 visual guide 를 넘을때마다 개행을 적용하였습니다.

2023-06-20 08:13 UTC, kimtaesoo99 commented on src/main/java/mju/chatuniv/board/domain/Board.java
> +    public void update(final BoardRequest boardRequest) {
BoardRequest를 의존하기때문에 만약 BoardRequest가 수정될경우 도메인에도 영향이 생깁니다. 따라서 결합도를 낮추기위해 매개변수에 직접적인 값들을 적용하도록 수정하였습니다.

2023-06-20 08:14 UTC, kimtaesoo99 commented on src/test/java/mju/chatuniv/board/BoardControllerIntegrationTest.java
> +            .header(HttpHeaders.AUTHORIZATION, BEARER_ + token)
이 부분은 따로 학습하고 적용해보겠습니다.

2023-06-23 02:58 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/dto/BoardAllResponse.java
> +    public static BoardAllResponse of(final List<BoardResponse> boards, final BoardPageInfo boardPageInfo) {
네이밍 변경해주세요

2023-06-23 02:59 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/dto/BoardPageInfo.java
> +    private BoardPageInfo(final int totalPage, final int nowPage,
차라리 파라미터 하나에 개행 한 줄은 어떨까요?
제 생각이니 별로라고 생각하면 냅두셔도 됩니다

2023-06-23 03:00 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/BoardService.java
> +            .collect(Collectors.toList());
`collectingAndThen()` 도 학습해보면 좋을 것 같습니다.
https://stackabuse.com/guide-to-java-8-collectors-collectingandthen/

2023-06-23 03:01 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/application/BoardService.java
> +            pageable.getPageSize(), Sort.by(BOARD_ID).descending());
개행이 어색합니다.
개행을 추가해서 가독성을 높여보는 것은 어떨까요?

2023-06-23 03:01 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +    public ResponseEntity<BoardResponse> update(@PathVariable("id") final Long boardId, @JwtLogin final Member member,
한 줄에 하나씩 해주는게 보기 좋을 것 같습니다.

2023-06-23 03:02 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +    @PatchMapping("/{id}")
지금은 `id`로 받아도 되겠지만 (하나 뿐이라), 추후에 PathVariable을 여러 개 쓴다면 id는 무엇을 의미하는지 혼동이 될 수 있을 것 같습니다. boardId로 통일 해보는 건 어떨까요?

2023-06-23 03:02 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
`ResponseEntity`를 생성해주는 것과, 빌더로 했을 때의 차이는 무엇일까요?
하나로 통일을 해주세요.

2023-06-23 03:03 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/domain/Board.java
> +    public static Board of(final String title, final String content, final Member member) {
네이밍 통일해주세요

2023-06-23 03:04 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/controller/BoardControllerIntegrationTest.java
> +        MemberResponse register = authService.register(new MemberCreateRequest("a3@a.com", "1234"));
이 부분은 Member API와 더불어 중복 해결의 방법이 있어보입니다.
이렇게 했을 때 좋은 점은 무엇일까요? 회의한 것처럼 장희형이랑 상의하면서 바꿔보면 좋을 것 같습니다.

2023-06-23 03:05 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/controller/BoardControllerIntegrationTest.java
> +            .header(HttpHeaders.AUTHORIZATION, BEARER_ + token)
이 방법말고 RestAssured의 `preemptive` 키워드를 학습해보십쇼

2023-06-23 03:05 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/controller/BoardControllerUnitTest.java
> +    private String createTokenByMember(Member member) {
이 부분또한 다른 단위 테스트에서 공통으로 사용할텐데 다른 방법을 찾아보세요
그리고 매개변수 final키워드가 없습니다~

2023-06-23 03:06 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/service/BoardServiceIntegrationTest.java
> +        assertSoftly(softAssertions -> {
assertAll 키워드를 학습해보세요

2023-06-23 03:06 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/service/BoardServiceIntegrationTest.java
> +            softAssertions.assertThat(board.getTitle()).isEqualTo("initTitle");
`usingRecursiveComparison()` 키워드를 학습해보세요~

2023-06-23 03:07 UTC, sosow0212 requested changes
리뷰 확인해주세요~

2023-06-24 02:14 UTC, JangAJang commented on src/main/java/mju/chatuniv/board/application/BoardService.java
> +        return BoardResponse.of(board);
제가 알기론, 
.from() : 입력받은 파라미터들을 이용해 하나의 결과가 나올 때
.of() : 입력받은 파라미터들을 이용해 나오는 결과가 여러 개 일 때 
인걸로 알고 있는데, 혹시 어떻게 생각하시는지 이야기해보는게 좋을 것 같습니다.

2023-06-25 02:46 UTC, JangAJang commented on src/test/java/mju/chatuniv/board/controller/BoardControllerIntegrationTest.java
> +        MemberResponse register = authService.register(new MemberCreateRequest("a3@a.com", "1234"));
추가로 @BeforeEach로 인해 port를 계속해서 초기화해줄 것 같은데, @PostConstruct로 하는건 어떨까 싶습니다.

2023-06-25 02:46 UTC, JangAJang commented on src/test/java/mju/chatuniv/board/controller/BoardControllerUnitTest.java
> +        BoardAllResponse boardAllResponse = BoardAllResponse.from(list, pageInfo);
이 부분들은 메서드를 분리해서 필요한 변수들을 따로 만드는 것이 좋아보입니다.

2023-06-25 06:38 UTC, kimtaesoo99 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +        return new ResponseEntity<>(HttpStatus.NO_CONTENT);
빌더를 사용하면 코드의 가독성이 높아지고, 체인 형식의 메서드 호출을 통해 필요한 속성을 설정할 수 있습니다

2023-06-25 08:09 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/board/controller/BoardControllerIntegrationTest.java
> +        MemberResponse register = authService.register(new MemberCreateRequest("a3@a.com", "1234"));
테스트 클래스 작동시 테스트 클래스의 테스트 컨텍스트가 로딩되고 각 테스트를 실행할 때마다 빈 컨텍스트가 생성됩니다. 그래서 테스트 클래스에 @BeforeEach()로 port를 초기화 해주는 것과 @PostConstruct로 port를 초기화 해주는 것의 결과가 동일합니다.(둘 다 테스트 메서드마다 실행됩니다.) 그래서 프로덕션 코드의 @PostConstruct와 같은 동작을 하는 메서드를 구현하기 위해 @BeforeTestClass와 @BeforeAll을 학습하였는데 @BeforeTestClass는 테스트 클래스가 생성되기 전에 먼저 실행되어 테스트 클래스와 테스트 컨텍스트가 달랐고 @BeforeAll은 @BeforeAll을 사용하는 메서드를 static으로 선언해야하여 관련 필드들을 static으로 변경해야해서 이 2가지 어노테이션을 코드에 적용하지는 않았습니다.

2023-06-26 09:22 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +
불필요한 개행 삭제해주세요.

2023-06-26 09:23 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +    public ResponseEntity<BoardResponse> create(@JwtLogin final Member member, @RequestBody @Valid final BoardRequest boardRequest) {
현재 전체적인 프로젝트에서 컨트롤러에서는 어노테이션으로 인해 파라미터 변수당 개행을 하나씩 추가해주고 있습니다.

어노테이션으로 인해 너무 길어지는 이유 때문에 컨트롤러에서만 개행 추가해주기로 한 점 숙지해주세요~

2023-06-26 09:24 UTC, sosow0212 commented on src/main/java/mju/chatuniv/board/controller/BoardController.java
> +        return ResponseEntity.status(HttpStatus.OK)
이 경우에 status를 굳이 사용할 필요가 있을까요?
200응답인 경우는 ok() 메서드를 사용해보는 건 어떨까요?

2023-06-26 09:25 UTC, sosow0212 commented on src/main/java/mju/chatuniv/member/domain/Member.java
> +    public boolean equals(Object o) {
equals hashCode를 재정의하신 이유가 있을까요?
불필요해 보입니다.

테스트에서 문제라면 다른 방법을 찾아보는 게 좋을 것 같습니다.
테스트는 테스트일뿐 프로덕션 코드에 영향을 미치는 건 좋아보이지 않습니다.

2023-06-26 09:27 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/controller/BoardControllerUnitTest.java
> +import static org.springframework.restdocs.payload.PayloadDocumentation.*;
import문에서 와일드카드는 삼가해주세요.
https://blog.devgenius.io/avoid-java-wildcard-imports-but-why-f219644cdd97

2023-06-26 09:27 UTC, sosow0212 commented on src/test/java/mju/chatuniv/board/controller/BoardControllerUnitTest.java
> +    @Value("${security.jwt.token.secret-key}")
다른 방법으로 검증하는 방법은 없을까요?

2023-06-26 09:27 UTC, sosow0212 requested changes
리뷰 확인해주세요~

2023-06-26 09:51 UTC, sosow0212 approved these changes

2023-06-26 09:52 UTC, JangAJang approved these changes

2023-06-26 09:54 UTC, merged