feat: 채팅방 대화 API 생성
sosow0212/ChatUniv pull request #81
Opened 2023-10-07 07:46 UTC by kimtaesoo99

- [x] 채팅방 대화 API생성
- [x] 기존 커멘드와 쿼리 분리
- [x] 테스트 추가 
- [x] adoc 댓글 예외 및 로직 추가

기존 commentService를 CommentRead 서비스 와 CommentWrite를 담당하는 서비스로 분리함

2023-10-07 08:04 UTC, JangAJang reviewed
디렉토리 구조 관련해서 생각나는 부분이 있어, 같이 작성했습니다.

2023-10-07 08:04 UTC, JangAJang commented on src/main/java/mju/chatuniv/comment/service/CommentService.java
지금 구조가 

```
CommentService
|--CommentReadService
    |-- BoardCommentQueryService
    |-- ConversationCommentQuerySerivice
|--CommentWriteService
    |-- BoardCommentService
    |-- ConversationCommentQueryService
```
 이런 구조로 되어있는 것 같은데, 그렇다면 readService, writeService로 디렉토리 구조를 분리하는 것은 어떨까요?
네이밍을 보았을 때, 추가적으로 readService, writeService를 더 만들어 사용할 수 있다는 가능성을 열고 구조화했는데, 
이를 디렉토리 구조로 분리했을 때, 더. 관리하기 수월할 것 같습니다.

2023-10-08 07:54 UTC, sosow0212 requested changes
몇 부분 수정해주세요~

2023-10-08 07:54 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/controller/ConversationCommentController.java
> +    public ResponseEntity<CommentAllResponse> findCommentsByConversation(@RequestParam(required = false, defaultValue = DEFAULT_PAGE) final Integer pageSize,
param에서 왜 ConversationId를 받나요?
restful에 맞게 해주세요~

2023-10-08 07:54 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/infrastructure/repository/BoardCommentQueryRepository.java
> +public class BoardCommentQueryRepository {
Repository는 테스트 하지 않아도 될까요?

2023-10-08 07:54 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/infrastructure/repository/BoardCommentQueryRepository.java
> +                .where(eqBoardId(boardId), (ltCommentId(commentId)))
이렇게 where를 구성한 이유가 있나요?

2023-10-08 07:54 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/service/CommentReadService.java
> +public interface CommentReadService extends CommentService {
CommentService -> CommentReadService --> xxxService 이런식으로 하신 이유가 있나요?
불필요한 것 같다고 생각이 드네요 혹시 이유가 무엇인가요?

2023-10-08 07:54 UTC, sosow0212 commented on src/test/java/mju/chatuniv/comment/controller/unit/ConversationCommentControllerUnitTest.java
> +                .andDo(customDocument("create_conversation",
다른 부분도 그렇고 pathvariable은 문서화 하지 않아도 될까요?
프론트는 해당 문서를 보고 만들텐데 다른 부분 포함해서 모든 부분에 문서화 체크해주세요 param 포함해서요

2023-10-08 07:54 UTC, sosow0212 commented on src/test/java/mju/chatuniv/comment/controller/unit/ConversationCommentControllerUnitTest.java
> +                        get("/api/conversations/comments/?pageSize=1&commentId=3"))
`/api/conversations/comments/?pageSize=1&commentId=3` 라는 url이 이상한 것 같아요 ex. `/?` 수정해주세요.

그리고 restful 원칙에 맞게 url 설계를 변경해주세요

2023-10-08 07:54 UTC, sosow0212 commented on src/test/java/mju/chatuniv/comment/service/integration/CommonCommentServiceIntegrationTest.java
> +            CommentWriteService commentService2 = commentServices2.get(index);
commentService2는 무엇인가요? 가독성이 안 좋아져서 네이밍을 차라리 commentWriteService로 하는게 좋을 것 같아요

2023-10-08 07:54 UTC, sosow0212 commented on src/test/java/mju/chatuniv/comment/service/integration/CommonCommentServiceIntegrationTest.java
> +class CommonCommentServiceIntegrationTest extends IntegrationTest {
해당 클래스의 테스트 가독성이 너무 안 좋은데 더 좋게 만들 순 없을까요?

2023-10-08 07:54 UTC, sosow0212 commented on src/test/java/mju/chatuniv/comment/service/unit/ConversationCommentServiceUnitTest.java
> +        member = Member.of("a@a.com", "password");
이미 있는 테스트 픽스쳐좀 써주세요

2023-10-08 07:54 UTC, sosow0212 commented on src/test/java/mju/chatuniv/comment/service/unit/ConversationCommentServiceUnitTest.java
> +        conversation = Conversation.of("hi", "hello", Chat.createDefault(member));
이 부분도 테스트 픽스쳐를 만들어서 쓰든 해주세요

2023-10-08 09:58 UTC, eom-tae-in commented on src/main/java/mju/chatuniv/comment/controller/ConversationCommentController.java
> +    public ResponseEntity<CommentAllResponse> findCommentsByConversation(@RequestParam(required = false, defaultValue = DEFAULT_PAGE) final Integer pageSize,
네 알겠습니다.

2023-10-08 10:03 UTC, eom-tae-in commented on src/main/java/mju/chatuniv/comment/infrastructure/repository/BoardCommentQueryRepository.java
> +public class BoardCommentQueryRepository {
코드를 작성할 때 레포지토리에 대한 테스트 생각하지 못했던 것 같습니다.
레포지토리 기능이 제대로 동작하는지 테스트 해봐야 할 것 같습니다. 추가하도록 하겠습니다.

2023-10-08 10:28 UTC, eom-tae-in commented on src/main/java/mju/chatuniv/comment/infrastructure/repository/BoardCommentQueryRepository.java
> +                .where(eqBoardId(boardId), (ltCommentId(commentId)))
where절을 통해 boardComment 테이블에서 매개변수로 받는 boardId 값이 같으면서 매개변수로 받는 commentId보다 작은 boardComment의 레코드들을 조회하도록 쿼리를 만들려고 했습니다.
위의 코드는 조건들을 and 연산으로 이어놓지 않아 eqBoardId가 null이여도 ltCommentId의 값이 있다면 ltCommentId에 대한 조건만 들어간 쿼리가 나가게 되네요.
수정하겠습니다. 앞으로는 좀 더 신경써서 구현하도록하겠습니다.

2023-10-09 06:28 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/comment/service/integration/CommonCommentServiceIntegrationTest.java
> +class CommonCommentServiceIntegrationTest extends IntegrationTest {
for 루프를 이용하여 테스트를 하도록 바꿔보았습니다. 좀 더 개선해야할 부분이 있다면 댓글 남겨주세요!

2023-10-09 06:28 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/comment/service/integration/CommonCommentServiceIntegrationTest.java
> +            CommentWriteService commentService2 = commentServices2.get(index);
알겠습니다.

2023-10-09 06:55 UTC, sosow0212 requested changes
몇 부분만 수정해주십쇼

2023-10-09 06:55 UTC, sosow0212 commented on src/main/java/mju/chatuniv/global/config/JpaAuditingConfig.java
> +    @PersistenceContext
개행 추가

2023-10-09 06:55 UTC, sosow0212 commented on src/test/java/mju/chatuniv/comment/repository/BoardCommentRepositoryTest.java
> +        Comment comment = commentRepository.findById(1L)
Optional로 받고 asta에서 isPresent로 검증한 후 추후에 get을 통해 꺼내서 비교해보는 건 어떨까요
그리고 다른 값도 검증하면 좋을 것 같아요

2023-10-09 06:55 UTC, sosow0212 commented on src/test/java/mju/chatuniv/helper/RepositoryTestHelper.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
테스트용 db가 있는데 따로 선언하신 이유가 뭔가요?

2023-10-09 06:55 UTC, sosow0212 commented on src/test/java/mju/chatuniv/helper/RepositoryTestHelper.java
> +public class RepositoryTestHelper {
`@DataJpaTest` 안에 Transactional이 있어서 데이블 초기화를 안해도 될 것 같은데 어떻게 생각하세요?
이 클래스가 필요해보이지 않습니다

해당 클래스를 사용하는 부분에서
@DataJpaTest + @Import(Querydsl)을 하면 될 것 같아요

2023-10-09 06:55 UTC, sosow0212 commented on src/test/java/mju/chatuniv/comment/repository/ConversationCommentRepositoryTest.java
> +        assertAll(
`usingRecursiveComparison`을 사용할 순 없을까요?

2023-10-09 06:55 UTC, sosow0212 commented on src/main/java/mju/chatuniv/comment/domain/BoardComment.java
> +    public Board getBoard() {
이부분도 그렇고 테스트에서 사용하려고 getter를 선언한 이유가 있나요? 다른 방법으로 확인할 수 있을 것 같아요

2023-10-09 06:55 UTC, sosow0212 commented on src/test/java/mju/chatuniv/comment/repository/BoardCommentRepositoryTest.java
> +                    System.out.println(save.getBoard().getId());
sout 지워주세요

2023-10-09 10:52 UTC, eom-tae-in commented on src/main/java/mju/chatuniv/comment/infrastructure/repository/BoardCommentQueryRepository.java
> +                .where(eqBoardId(boardId), (ltCommentId(commentId)))
조건을 모두 메서드로 분리하여 각각 BooleanExpression으로 조건에 대한 값을 리턴받도록 하였습니다. 코드의 가독성을 높이고 BooleanExpression으로 null이 반환될 경우 where절에서 조건은 무시되기 때문에 안전하다고 생각하여 다음과 같이 구성했습니다.

2023-10-09 10:58 UTC, eom-tae-in commented on src/main/java/mju/chatuniv/comment/service/CommentReadService.java
> +public interface CommentReadService extends CommentService {
기존에 테스트에서 CommentService 타입으로 빈 조회를 하여 동적 테스트를 돌리고 있었습니다. 우선 코드의 변경을 최소화 하기위해 CommentService를 extent하는 CommentReadService와 CommentWriteService를 만들게 되었습니다. 테스트 코드를 작성하다보니 이렇게 CommentService를 extends하는 기존의 방식 보다는 쓰기와 읽기를 따로 강제하기 위한 CommentReadService와 CommentWriteService만을 가지고 작성하는게 좋다고 생각했습니다. 그래서 CommentService -> CommentReadService 이렇게 변경하였습니다.

2023-10-09 10:58 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/comment/controller/unit/ConversationCommentControllerUnitTest.java
> +                .andDo(customDocument("create_conversation",
알겠습니다.

2023-10-09 10:59 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/comment/service/unit/ConversationCommentServiceUnitTest.java
> +        member = Member.of("a@a.com", "password");
알겠습니다. 추가적으로 테스트에 필요한 픽스처도 추가하도록 하겠습니다.

2023-10-09 11:04 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/comment/repository/BoardCommentRepositoryTest.java
> +        Comment comment = commentRepository.findById(1L)
아 그런 방법이 있었네요. 수정하도록 하겠습니다.

2023-10-09 13:15 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/comment/repository/BoardCommentRepositoryTest.java
> +                    System.out.println(save.getBoard().getId());
알겠습니다.

2023-10-09 13:38 UTC, eom-tae-in commented on src/main/java/mju/chatuniv/comment/service/CommentService.java
테스트 코드를 작성하면서 더더욱 지금 구조가 잘못되어있다는 것을 알았습니다. 그래서 불필요해진 CommentService 인터페이스를 제거하였습니다.

2023-10-09 13:40 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/helper/RepositoryTestHelper.java
> +@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)를 주어야 설정한 테스트용 데이터베이스가 적용되는 줄 알았습니다....ㅎㅎ
찾아보니 테스트용 데이터베이스는 별도의 설정이 필요하지 않다는 것을 알게 되었습니다.
리뷰 감사합니다!

2023-10-09 13:47 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/helper/RepositoryTestHelper.java
> +public class RepositoryTestHelper {
로컬 환경에서 테스트를 진행해보고 관련 자료들을 찾아보니 테스트용 테이터 베이스의 MODE=MySQL 부분이 H2 DB의 호환 모드를 MySQL로 설정하는 것이여서, 레포지토리 테스트를 진행하고 롤백이 되도  AUTO_INCREMENT 컬럼 값이 증가하게 되는 것 같습니다. 그래서 h2 데이터 베이스의 테이블의 AUTO_INCREMENT 컬럼 값을 1로 초기화 시키는 작업이 필요해보였습니다.
그래서 쿼리를 h2 데이터베이스에 맞게 수정해보았습니다.

2023-10-09 13:48 UTC, eom-tae-in commented on src/main/java/mju/chatuniv/comment/domain/BoardComment.java
> +    public Board getBoard() {
언급해주신 usingRecursiveComparison으로 이 문제를 해결할 수 있었습니다.

2023-10-09 13:48 UTC, eom-tae-in commented on src/test/java/mju/chatuniv/comment/repository/ConversationCommentRepositoryTest.java
> +        assertAll(
알겠습니다.

2023-10-09 14:09 UTC, merged